[task]
prompt = "Search for the ovulation calculator and enter Mar 1 as the first date of the period and calculate the date of ovulation and pregnancy test day."
url = "https://www.webmd.com/"
tags = ["online-mind2web", "hard", "reachable"]
