[task]
prompt = "Check the specifications of the best-selling HP FHD laptop with 16 GB RAM and core i7 running on Windows 11."
url = "https://www.bestbuy.com/"
tags = ["online-mind2web", "hard", "open", "smoke"]
