[task]
prompt = "I want to purchase an open-box Samsung Galaxy S25 Plus in excellent condition and trade in a green Galaxy S22 5G (Verizon, 128GB), with a perfect screen, in good condition. How much would it cost?"
url = "https://www.bestbuy.com/"
tags = ["online-mind2web", "hard", "open"]
