[task]
prompt = "Search for papers related to reinforcement learning under the topics of computer science and mathematics on arxiv, with recent submission dates between September 2024 and January 2025."
url = "https://arxiv.org/"
tags = ["online-mind2web", "hard", "reachable"]
